accumulate_grad_batches: 1
amp: false
aux_l1_loss: true
aux_percep_loss: false
aux_ssim_loss: false
base_config:
- ../base/diffsr_base.yaml
- ../data/df2k4x_sam.yaml
batch_size: 64
beta_end: 0.02
beta_s: 0.008
beta_schedule: cosine
binary_data_dir: /data2/lichenyue/Medical-SAM2-main/data/train/df2k4x_sam
check_val_every_n_epoch: 10
clip_grad_norm: 10
clip_input: true
crop_size: 320
data_augmentation: false
data_interp: bicubic
debug: false
decay_steps: 200000
denoise_fn: unet
ds_workers: 1
endless: false
eval_batch_size: 1
fix_rrdb: true
gen_dir_name: ''
gn_groups: 0
hidden_size: 64
infer: false
load_ckpt: ''
loss_type: l1
lr: 0.0002
max_epochs: 1000
max_updates: 400000
num_ckpt_keep: 100
num_sanity_val_steps: 2
num_workers: 8
patch_size: 160
pred_noise: true
print_arch: false
print_nan_grads: false
res: true
res_rescale: 2.0
resume_from_checkpoint: 0
rrdb_ckpt: ''
rrdb_num_block: 17
rrdb_num_feat: 64
sam_config:
  cond_sam: false
  mask_coefficient: true
  p_losses_sam: true
sam_data_config:
  all_same_mask_to_zero: false
  normalize_01: false
  normalize_11: false
save_best: true
save_codes:
- configs
- models_sr
- tasks
- utils_sr
save_intermediate: false
seed: 1234
show_training_process: false
sr_scale: 4
style_interp: false
tb_log_interval: 100
test_batch_size: 1
test_crop_size:
- 2040
- 2040
test_input_dir: ''
test_save_png: false
test_thresh_size: 0
thresh_size: 160
timesteps: 100
trainer_cls: tasks.srdiff_df2k_sam.SRDiffDf2k_sam
unet_dim_mults: 1|2|3|4
up_input: false
use_attn: false
use_rrdb: true
use_wn: false
val_check_interval: 4000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_steps: 4
weight_init: false
work_dir: /home/cli348/New/exp/checkpoints/sam_diffsr_df2k4x
